server:
  port: 8001
  servlet:
    context-path: /api/v1

spring:
  application:
    name: products-service
  jackson:
    serialization:
      indent-output: false
  profiles:
    include:
      - security
      - db