INSERT INTO categories (id, name)
VALUES (gen_random_uuid(), 'Электроника и гаджеты'),
       (gen_random_uuid(), 'Одежда'),
       (gen_random_uuid(), 'Обувь'),
       (gen_random_uuid(), 'Бытовая техника'),
       (gen_random_uuid(), 'Красота и здоровье'),
       (gen_random_uuid(), 'Дом и сад'),
       (gen_random_uuid(), 'Детские товары'),
       (gen_random_uuid(), 'Спорт и отдыха'),
       (gen_random_uuid(), 'Автотовары'),
       (gen_random_uuid(), 'Зоотовары'),
       (gen_random_uuid(), 'Книги'),
       (gen_random_uuid(), 'Продукты питания'),
       (gen_random_uuid(), 'Канцелярские товары'),
       (gen_random_uuid(), 'Игры и консоли'),
       (gen_random_uuid(), 'Мебель'),
       (gen_random_uuid(), 'Ювелирные украшения'),
       (gen_random_uuid(), 'Строительство и ремонт'),
       (gen_random_uuid(), 'Аптека и БАД'),
       (gen_random_uuid(), 'Хобби и творчества'),
       (gen_random_uuid(), 'Аксессуары');