openapi: 3.0.3
info:
  title: Products Service API
  version: 1.0.0
  description: >
    REST API for managing products

servers:
  - url: https://localhost:8001

paths:
  # Categories
  /categories:
    parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 0
      - name: size
        in: query
        schema:
          type: integer
          default: 20
    get:
      tags:
        - Categories
      operationId: categoriesGet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryPageResponse"

  # Products
  /products:
    get:
      tags:
        - Products
      operationId: productsGet
      parameters:
        - name: categoryId
          in: query
          schema:
            type: string
            format: uuid
        - name: merchantId
          in: query
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductPageResponse"
    post:
      tags:
        - Products
      summary: Создать новый товар
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateRequest'
      responses:
        '200':
          description: Товар успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
  /products/{productId}:
    get:
      tags:
        - Products
      operationId: productsGetById
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
    patch:
      tags:
        - Products
      operationId: productUpdate
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdateRequest'
      responses:
        '200':
          description: OK
  /products/reserve:
    post:
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductReserveRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductResponse'

  # Reviews
  /products/{productId}/reviews:
    get:
      tags:
        - Reviews
      operationId: productReviewsGet
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewPageResponse'
    post:
      tags:
        - Reviews
      operationId: reviewCreate
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewCreateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponse'

components:
  schemas:
    CategoryResponse:
      type: object
      required: [ id, name ]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    ProductCreateRequest:
      type: object
      required: [ categoryId, title, price, quantityInStock ]
      properties:
        categoryId:
          type: string
          format: uuid
        title:
          type: string
          minLength: 3
        description:
          type: string
        price:
          type: number
          format: double
        quantityInStock:
          type: integer
          minimum: 0

    ProductUpdateRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        quantityInStock:
          type: integer
          minimum: 0
        isActive:
          type: boolean
    ProductResponse:
      type: object
      required: [ id, merchantId, categoryId, title, price, quantityInStock, averageRating, reviewCount, isActive ]
      properties:
        id:
          type: string
          format: uuid
        merchantId:
          type: string
          format: uuid
        category:
          $ref: "#/components/schemas/CategoryResponse"
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        quantityInStock:
          type: integer
        averageRating:
          type: number
          format: double
        reviewCount:
          type: integer
        isActive:
          type: boolean
    ProductReserveRequest:
      type: array
      items:
        type: object
        required: [ productId, quantity ]
        properties:
          productId:
            type: string
            format: uuid
          quantity:
            type: integer
            minimum: 1
            maximum: 10
    ReviewCreateRequest:
      type: object
      required: [ rating ]
      properties:
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
    ReviewResponse:
      type: object
      required: [ id, customerId, rating, createdAt ]
      properties:
        id:
          type: string
          format: uuid
        productId:
          type: string
          format: uuid
        customerId:
          type: string
          format: uuid
        rating:
          type: integer
        comment:
          type: string
        createdAt:
          type: integer
          format: int64
    ProductPageResponse:
      allOf:
        - $ref: "#/components/schemas/PageResponse"
        - properties:
            items:
              items:
                $ref: "#/components/schemas/ProductResponse"
    CategoryPageResponse:
      allOf:
        - $ref: "#/components/schemas/PageResponse"
        - properties:
            items:
              items:
                $ref: "#/components/schemas/CategoryResponse"
    ReviewPageResponse:
      allOf:
        - $ref: "#/components/schemas/PageResponse"
        - properties:
            items:
              items:
                $ref: "#/components/schemas/ReviewResponse"
    OrderItem:
      type: object
      required: [ id, productId, merchantId, quantity, price ]
      properties:
        id:
          type: string
          format: uuid
        productId:
          type: string
          format: uuid
        merchantId:
          type: string
          format: uuid
        quantity:
          type: integer
        price:
          type: number
          format: double

    # Events
    OrderCanceledEvent:
      type: object
      required: [ id, customerId, items ]
      properties:
        id:
          type: string
          format: uuid
        customerId:
          type: string
          format: uuid
        shippingAddressId:
          type: string
          format: uuid
        totalAmount:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        createdAt:
          type: integer
          format: int64

    PageResponse:
      type: object
      required: [ page, size, items ]
      properties:
        page:
          type: integer
        page_size:
          type: integer
        total_pages:
          type: integer
        total_items:
          type: integer
        items:
          type: array
          items:
            type: object
            properties: { }