spring:
  config:
    activate:
      on-profile: db
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  flyway:
    schemas: orders
    default-schema: orders
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1200000
      maximum-pool-size: 4
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      properties:
        show_sql: true
        highlight_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true
    properties:
      hibernate:
        default_schema: orders