server:
  port: 8000
  servlet:
    context-path: /api/v1
  tomcat:
    threads:
      max: 50

spring:
  application:
    name: users-service
  jackson:
    serialization:
      indent-output: false
  main:
    lazy-initialization: true
  profiles:
    include:
      - db
      - app
      - data