app:
  data:
    notifications:
      text:
        merchant-verified: Ваш аккаунт продавца c id \#%s успешно подтверждён. Теперь вы можете размещать товары и пользоваться всеми возможностями платформы.